### PR TITLE
reverting to before entity replaced all methods 

### PR DESCRIPTION
**Pull request by alistairong**
to facilitate easier split of person, module, occasion.

### CODE REVIEW

**Comment by alistairong** [comment]
reverted the commit with entity, will be adding and modifying test for the XmlAdaptedModule, Module,

**Comment by waytan** [comment]
I think we'll work with this (i.e. the original arrangement first). The logic/style of the individual commands can be reconfigured by the relevant people accordingly. Thanks!

**Comment by KongZijin** [comment]
Reviewed.

**Comment by alistairong** [comment]
seems like github's travis is down, and cannot check properly.

**Pull request merged**
